# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'tinyowsxmlgenerator.ui'
#
# Created: Wed Feb 25 20:50:39 2015
#      by: PyQt4 UI code generator 4.11.1
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_TinyowsXmlGenerator(object):
    def setupUi(self, TinyowsXmlGenerator):
        TinyowsXmlGenerator.setObjectName(_fromUtf8("TinyowsXmlGenerator"))
        TinyowsXmlGenerator.resize(729, 606)
        TinyowsXmlGenerator.setSizeGripEnabled(True)
        self.gridLayout = QtGui.QGridLayout(TinyowsXmlGenerator)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.buttonBox = QtGui.QDialogButtonBox(TinyowsXmlGenerator)
        self.buttonBox.setStandardButtons(QtGui.QDialogButtonBox.Cancel|QtGui.QDialogButtonBox.Help|QtGui.QDialogButtonBox.Ok)
        self.buttonBox.setObjectName(_fromUtf8("buttonBox"))
        self.gridLayout.addWidget(self.buttonBox, 2, 0, 1, 2)
        self.tabWidget = QtGui.QTabWidget(TinyowsXmlGenerator)
        sizePolicy = QtGui.QSizePolicy(QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.tabWidget.sizePolicy().hasHeightForWidth())
        self.tabWidget.setSizePolicy(sizePolicy)
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.gridLayout_3 = QtGui.QGridLayout(self.tab)
        self.gridLayout_3.setObjectName(_fromUtf8("gridLayout_3"))
        self.label_5 = QtGui.QLabel(self.tab)
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.gridLayout_3.addWidget(self.label_5, 1, 2, 1, 1)
        self.label_15 = QtGui.QLabel(self.tab)
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.gridLayout_3.addWidget(self.label_15, 6, 2, 1, 1)
        self.label_4 = QtGui.QLabel(self.tab)
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.gridLayout_3.addWidget(self.label_4, 1, 0, 1, 1)
        self.txtTinyowsLogLevel_2 = QtGui.QLineEdit(self.tab)
        self.txtTinyowsLogLevel_2.setObjectName(_fromUtf8("txtTinyowsLogLevel_2"))
        self.gridLayout_3.addWidget(self.txtTinyowsLogLevel_2, 2, 3, 1, 1)
        self.txtTinyowsOnlineResource = QtGui.QLineEdit(self.tab)
        self.txtTinyowsOnlineResource.setObjectName(_fromUtf8("txtTinyowsOnlineResource"))
        self.gridLayout_3.addWidget(self.txtTinyowsOnlineResource, 1, 1, 1, 1)
        self.txtTinyowsLog = QtGui.QLineEdit(self.tab)
        self.txtTinyowsLog.setObjectName(_fromUtf8("txtTinyowsLog"))
        self.gridLayout_3.addWidget(self.txtTinyowsLog, 2, 1, 1, 1)
        self.txtXmlConfigFilePath = QtGui.QLineEdit(self.tab)
        self.txtXmlConfigFilePath.setText(_fromUtf8(""))
        self.txtXmlConfigFilePath.setObjectName(_fromUtf8("txtXmlConfigFilePath"))
        self.gridLayout_3.addWidget(self.txtXmlConfigFilePath, 0, 1, 1, 1)
        self.txtTinyowsCheckValidGeom = QtGui.QLineEdit(self.tab)
        self.txtTinyowsCheckValidGeom.setObjectName(_fromUtf8("txtTinyowsCheckValidGeom"))
        self.gridLayout_3.addWidget(self.txtTinyowsCheckValidGeom, 5, 3, 1, 1)
        self.txtTinyowsCheckSchema = QtGui.QLineEdit(self.tab)
        self.txtTinyowsCheckSchema.setObjectName(_fromUtf8("txtTinyowsCheckSchema"))
        self.gridLayout_3.addWidget(self.txtTinyowsCheckSchema, 5, 1, 1, 1)
        self.label_9 = QtGui.QLabel(self.tab)
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.gridLayout_3.addWidget(self.label_9, 3, 2, 1, 1)
        self.txtTinyowsEstimatedExtent = QtGui.QLineEdit(self.tab)
        self.txtTinyowsEstimatedExtent.setObjectName(_fromUtf8("txtTinyowsEstimatedExtent"))
        self.gridLayout_3.addWidget(self.txtTinyowsEstimatedExtent, 4, 3, 1, 1)
        self.txtTinyowsMeterPrecision = QtGui.QLineEdit(self.tab)
        self.txtTinyowsMeterPrecision.setObjectName(_fromUtf8("txtTinyowsMeterPrecision"))
        self.gridLayout_3.addWidget(self.txtTinyowsMeterPrecision, 3, 3, 1, 1)
        self.txtTinyowsLogLevel = QtGui.QLabel(self.tab)
        self.txtTinyowsLogLevel.setObjectName(_fromUtf8("txtTinyowsLogLevel"))
        self.gridLayout_3.addWidget(self.txtTinyowsLogLevel, 2, 2, 1, 1)
        self.txtTinyowsDegreePrecision = QtGui.QLineEdit(self.tab)
        self.txtTinyowsDegreePrecision.setObjectName(_fromUtf8("txtTinyowsDegreePrecision"))
        self.gridLayout_3.addWidget(self.txtTinyowsDegreePrecision, 3, 1, 1, 1)
        self.txtTinyowsExposePk = QtGui.QLineEdit(self.tab)
        self.txtTinyowsExposePk.setObjectName(_fromUtf8("txtTinyowsExposePk"))
        self.gridLayout_3.addWidget(self.txtTinyowsExposePk, 6, 3, 1, 1)
        self.label_12 = QtGui.QLabel(self.tab)
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.gridLayout_3.addWidget(self.label_12, 5, 0, 1, 1)
        self.txtTinyowsEncoding = QtGui.QLineEdit(self.tab)
        self.txtTinyowsEncoding.setObjectName(_fromUtf8("txtTinyowsEncoding"))
        self.gridLayout_3.addWidget(self.txtTinyowsEncoding, 6, 1, 1, 1)
        self.label_16 = QtGui.QLabel(self.tab)
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.gridLayout_3.addWidget(self.label_16, 7, 0, 1, 1)
        self.label_14 = QtGui.QLabel(self.tab)
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.gridLayout_3.addWidget(self.label_14, 6, 0, 1, 1)
        self.label_11 = QtGui.QLabel(self.tab)
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.gridLayout_3.addWidget(self.label_11, 4, 2, 1, 1)
        self.label_6 = QtGui.QLabel(self.tab)
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.gridLayout_3.addWidget(self.label_6, 2, 0, 1, 1)
        self.label = QtGui.QLabel(self.tab)
        self.label.setObjectName(_fromUtf8("label"))
        self.gridLayout_3.addWidget(self.label, 0, 0, 1, 1)
        self.txtTinyowsSchemaDir = QtGui.QLineEdit(self.tab)
        self.txtTinyowsSchemaDir.setObjectName(_fromUtf8("txtTinyowsSchemaDir"))
        self.gridLayout_3.addWidget(self.txtTinyowsSchemaDir, 1, 3, 1, 1)
        self.label_8 = QtGui.QLabel(self.tab)
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.gridLayout_3.addWidget(self.label_8, 3, 0, 1, 1)
        self.label_10 = QtGui.QLabel(self.tab)
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.gridLayout_3.addWidget(self.label_10, 4, 0, 1, 1)
        self.label_13 = QtGui.QLabel(self.tab)
        self.label_13.setObjectName(_fromUtf8("label_13"))
        self.gridLayout_3.addWidget(self.label_13, 5, 2, 1, 1)
        self.txtTinyowsWfsDefaultVersion = QtGui.QLineEdit(self.tab)
        self.txtTinyowsWfsDefaultVersion.setObjectName(_fromUtf8("txtTinyowsWfsDefaultVersion"))
        self.gridLayout_3.addWidget(self.txtTinyowsWfsDefaultVersion, 7, 1, 1, 1)
        self.txtTinyowsDisplayBbox = QtGui.QLineEdit(self.tab)
        self.txtTinyowsDisplayBbox.setObjectName(_fromUtf8("txtTinyowsDisplayBbox"))
        self.gridLayout_3.addWidget(self.txtTinyowsDisplayBbox, 4, 1, 1, 1)
        self.btnChooseFile = QtGui.QToolButton(self.tab)
        self.btnChooseFile.setObjectName(_fromUtf8("btnChooseFile"))
        self.gridLayout_3.addWidget(self.btnChooseFile, 0, 2, 1, 1)
        spacerItem = QtGui.QSpacerItem(20, 150, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_3.addItem(spacerItem, 8, 1, 1, 1)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.gridLayout_7 = QtGui.QGridLayout(self.tab_2)
        self.gridLayout_7.setObjectName(_fromUtf8("gridLayout_7"))
        self.txtPostgresPassword = QtGui.QLineEdit(self.tab_2)
        self.txtPostgresPassword.setObjectName(_fromUtf8("txtPostgresPassword"))
        self.gridLayout_7.addWidget(self.txtPostgresPassword, 1, 1, 1, 1)
        self.txtPostgresUser = QtGui.QLineEdit(self.tab_2)
        self.txtPostgresUser.setObjectName(_fromUtf8("txtPostgresUser"))
        self.gridLayout_7.addWidget(self.txtPostgresUser, 0, 3, 1, 1)
        spacerItem1 = QtGui.QSpacerItem(20, 300, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_7.addItem(spacerItem1, 3, 0, 1, 3)
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.gridLayout_7.addWidget(self.label_2, 0, 0, 1, 1)
        self.txtPostgresDbname = QtGui.QLineEdit(self.tab_2)
        self.txtPostgresDbname.setObjectName(_fromUtf8("txtPostgresDbname"))
        self.gridLayout_7.addWidget(self.txtPostgresDbname, 1, 3, 1, 1)
        self.label_17 = QtGui.QLabel(self.tab_2)
        self.label_17.setObjectName(_fromUtf8("label_17"))
        self.gridLayout_7.addWidget(self.label_17, 1, 2, 1, 1)
        self.label_7 = QtGui.QLabel(self.tab_2)
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.gridLayout_7.addWidget(self.label_7, 1, 0, 1, 1)
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.gridLayout_7.addWidget(self.label_3, 0, 2, 1, 1)
        self.txtPostgresHost = QtGui.QLineEdit(self.tab_2)
        self.txtPostgresHost.setObjectName(_fromUtf8("txtPostgresHost"))
        self.gridLayout_7.addWidget(self.txtPostgresHost, 0, 1, 1, 1)
        self.label_18 = QtGui.QLabel(self.tab_2)
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.gridLayout_7.addWidget(self.label_18, 2, 0, 1, 1)
        self.txtPostgresPort = QtGui.QLineEdit(self.tab_2)
        self.txtPostgresPort.setObjectName(_fromUtf8("txtPostgresPort"))
        self.gridLayout_7.addWidget(self.txtPostgresPort, 2, 1, 1, 1)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.tab_3 = QtGui.QWidget()
        self.tab_3.setObjectName(_fromUtf8("tab_3"))
        self.gridLayout_8 = QtGui.QGridLayout(self.tab_3)
        self.gridLayout_8.setObjectName(_fromUtf8("gridLayout_8"))
        self.txtMetadataAccessConstraints = QtGui.QLineEdit(self.tab_3)
        self.txtMetadataAccessConstraints.setObjectName(_fromUtf8("txtMetadataAccessConstraints"))
        self.gridLayout_8.addWidget(self.txtMetadataAccessConstraints, 5, 1, 1, 1)
        self.label_24 = QtGui.QLabel(self.tab_3)
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.gridLayout_8.addWidget(self.label_24, 5, 0, 1, 1)
        self.txtMetadataName = QtGui.QLineEdit(self.tab_3)
        self.txtMetadataName.setObjectName(_fromUtf8("txtMetadataName"))
        self.gridLayout_8.addWidget(self.txtMetadataName, 3, 1, 1, 1)
        self.txtMetadataTitle = QtGui.QLineEdit(self.tab_3)
        self.txtMetadataTitle.setObjectName(_fromUtf8("txtMetadataTitle"))
        self.gridLayout_8.addWidget(self.txtMetadataTitle, 3, 3, 1, 1)
        self.label_22 = QtGui.QLabel(self.tab_3)
        self.label_22.setObjectName(_fromUtf8("label_22"))
        self.gridLayout_8.addWidget(self.label_22, 4, 0, 1, 1)
        self.txtMetadataKeywords = QtGui.QLineEdit(self.tab_3)
        self.txtMetadataKeywords.setObjectName(_fromUtf8("txtMetadataKeywords"))
        self.gridLayout_8.addWidget(self.txtMetadataKeywords, 4, 1, 1, 1)
        self.label_23 = QtGui.QLabel(self.tab_3)
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.gridLayout_8.addWidget(self.label_23, 4, 2, 1, 1)
        self.txtMetadataFees = QtGui.QLineEdit(self.tab_3)
        self.txtMetadataFees.setObjectName(_fromUtf8("txtMetadataFees"))
        self.gridLayout_8.addWidget(self.txtMetadataFees, 4, 3, 1, 1)
        self.label_20 = QtGui.QLabel(self.tab_3)
        self.label_20.setObjectName(_fromUtf8("label_20"))
        self.gridLayout_8.addWidget(self.label_20, 3, 0, 1, 1)
        self.label_21 = QtGui.QLabel(self.tab_3)
        self.label_21.setObjectName(_fromUtf8("label_21"))
        self.gridLayout_8.addWidget(self.label_21, 3, 2, 1, 1)
        spacerItem2 = QtGui.QSpacerItem(20, 300, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_8.addItem(spacerItem2, 6, 1, 1, 1)
        self.tabWidget.addTab(self.tab_3, _fromUtf8(""))
        self.tab_4 = QtGui.QWidget()
        self.tab_4.setObjectName(_fromUtf8("tab_4"))
        self.gridLayout_31 = QtGui.QGridLayout(self.tab_4)
        self.gridLayout_31.setObjectName(_fromUtf8("gridLayout_31"))
        spacerItem3 = QtGui.QSpacerItem(20, 350, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Fixed)
        self.gridLayout_31.addItem(spacerItem3, 2, 1, 1, 1)
        self.txtLayerWritable = QtGui.QLineEdit(self.tab_4)
        self.txtLayerWritable.setObjectName(_fromUtf8("txtLayerWritable"))
        self.gridLayout_31.addWidget(self.txtLayerWritable, 1, 3, 1, 1)
        self.label_41 = QtGui.QLabel(self.tab_4)
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.gridLayout_31.addWidget(self.label_41, 0, 0, 1, 1)
        self.label_61 = QtGui.QLabel(self.tab_4)
        self.label_61.setObjectName(_fromUtf8("label_61"))
        self.gridLayout_31.addWidget(self.label_61, 1, 0, 1, 1)
        self.txtTinyowsLogLevel1 = QtGui.QLabel(self.tab_4)
        self.txtTinyowsLogLevel1.setObjectName(_fromUtf8("txtTinyowsLogLevel1"))
        self.gridLayout_31.addWidget(self.txtTinyowsLogLevel1, 1, 2, 1, 1)
        self.txtLayerRetrievable = QtGui.QLineEdit(self.tab_4)
        self.txtLayerRetrievable.setObjectName(_fromUtf8("txtLayerRetrievable"))
        self.gridLayout_31.addWidget(self.txtLayerRetrievable, 1, 1, 1, 1)
        self.label_51 = QtGui.QLabel(self.tab_4)
        self.label_51.setObjectName(_fromUtf8("label_51"))
        self.gridLayout_31.addWidget(self.label_51, 0, 2, 1, 1)
        self.txtLayerNsUri = QtGui.QLineEdit(self.tab_4)
        self.txtLayerNsUri.setObjectName(_fromUtf8("txtLayerNsUri"))
        self.gridLayout_31.addWidget(self.txtLayerNsUri, 0, 3, 1, 1)
        self.txtLayerNsPrefix = QtGui.QLineEdit(self.tab_4)
        self.txtLayerNsPrefix.setObjectName(_fromUtf8("txtLayerNsPrefix"))
        self.gridLayout_31.addWidget(self.txtLayerNsPrefix, 0, 1, 1, 1)
        self.tabWidget.addTab(self.tab_4, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        self.label.setBuddy(self.txtXmlConfigFilePath)

        self.retranslateUi(TinyowsXmlGenerator)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("rejected()")), TinyowsXmlGenerator.reject)
        QtCore.QObject.connect(self.buttonBox, QtCore.SIGNAL(_fromUtf8("accepted()")), TinyowsXmlGenerator.accept)
        QtCore.QMetaObject.connectSlotsByName(TinyowsXmlGenerator)
        TinyowsXmlGenerator.setTabOrder(self.txtXmlConfigFilePath, self.txtTinyowsOnlineResource)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsOnlineResource, self.txtTinyowsSchemaDir)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsSchemaDir, self.txtTinyowsLog)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsLog, self.txtTinyowsLogLevel_2)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsLogLevel_2, self.txtTinyowsDegreePrecision)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsDegreePrecision, self.txtTinyowsMeterPrecision)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsMeterPrecision, self.txtTinyowsDisplayBbox)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsDisplayBbox, self.txtTinyowsEstimatedExtent)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsEstimatedExtent, self.txtTinyowsCheckSchema)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsCheckSchema, self.txtTinyowsCheckValidGeom)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsCheckValidGeom, self.txtTinyowsEncoding)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsEncoding, self.txtTinyowsExposePk)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsExposePk, self.txtTinyowsWfsDefaultVersion)
        TinyowsXmlGenerator.setTabOrder(self.txtTinyowsWfsDefaultVersion, self.txtPostgresHost)
        TinyowsXmlGenerator.setTabOrder(self.txtPostgresHost, self.txtPostgresUser)
        TinyowsXmlGenerator.setTabOrder(self.txtPostgresUser, self.txtPostgresPassword)
        TinyowsXmlGenerator.setTabOrder(self.txtPostgresPassword, self.txtPostgresDbname)
        TinyowsXmlGenerator.setTabOrder(self.txtPostgresDbname, self.txtPostgresPort)
        TinyowsXmlGenerator.setTabOrder(self.txtPostgresPort, self.txtMetadataName)
        TinyowsXmlGenerator.setTabOrder(self.txtMetadataName, self.txtMetadataTitle)
        TinyowsXmlGenerator.setTabOrder(self.txtMetadataTitle, self.txtMetadataKeywords)
        TinyowsXmlGenerator.setTabOrder(self.txtMetadataKeywords, self.txtMetadataFees)
        TinyowsXmlGenerator.setTabOrder(self.txtMetadataFees, self.txtMetadataAccessConstraints)
        TinyowsXmlGenerator.setTabOrder(self.txtMetadataAccessConstraints, self.tabWidget)
        TinyowsXmlGenerator.setTabOrder(self.tabWidget, self.btnChooseFile)

    def retranslateUi(self, TinyowsXmlGenerator):
        TinyowsXmlGenerator.setWindowTitle(_translate("TinyowsXmlGenerator", "TinyOws XML Generator", None))
        self.label_5.setText(_translate("TinyowsXmlGenerator", "schema_dir*", None))
        self.label_15.setText(_translate("TinyowsXmlGenerator", "expose_pk", None))
        self.label_4.setText(_translate("TinyowsXmlGenerator", "online_resource*", None))
        self.txtTinyowsLogLevel_2.setText(_translate("TinyowsXmlGenerator", "15", None))
        self.txtTinyowsOnlineResource.setText(_translate("TinyowsXmlGenerator", "http://127.0.0.1/cgi-bin/tinyows.exe", None))
        self.txtTinyowsLog.setText(_translate("TinyowsXmlGenerator", "C:/inetpub/wwwroot/tinyows/tinyows.log", None))
        self.txtXmlConfigFilePath.setToolTip(_translate("TinyowsXmlGenerator", "Name for the map file to be created from the QGIS project file", None))
        self.txtTinyowsCheckSchema.setText(_translate("TinyowsXmlGenerator", "0", None))
        self.label_9.setText(_translate("TinyowsXmlGenerator", "meter_precision", None))
        self.txtTinyowsLogLevel.setText(_translate("TinyowsXmlGenerator", "log_level", None))
        self.label_12.setText(_translate("TinyowsXmlGenerator", "check_schema", None))
        self.label_16.setText(_translate("TinyowsXmlGenerator", "wfs_default_version", None))
        self.label_14.setText(_translate("TinyowsXmlGenerator", "encoding", None))
        self.label_11.setText(_translate("TinyowsXmlGenerator", "estimated_extent", None))
        self.label_6.setText(_translate("TinyowsXmlGenerator", "log", None))
        self.label.setText(_translate("TinyowsXmlGenerator", "XML config file", None))
        self.txtTinyowsSchemaDir.setText(_translate("TinyowsXmlGenerator", "C:/inetpub/wwwroot/tinyows/schema/", None))
        self.label_8.setText(_translate("TinyowsXmlGenerator", "degree_precision", None))
        self.label_10.setText(_translate("TinyowsXmlGenerator", "display_bbox", None))
        self.label_13.setText(_translate("TinyowsXmlGenerator", "check_valid_geom", None))
        self.btnChooseFile.setText(_translate("TinyowsXmlGenerator", "...", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("TinyowsXmlGenerator", "Tinyows", None))
        self.label_2.setText(_translate("TinyowsXmlGenerator", "host", None))
        self.label_17.setText(_translate("TinyowsXmlGenerator", "dbname", None))
        self.label_7.setText(_translate("TinyowsXmlGenerator", "password", None))
        self.label_3.setText(_translate("TinyowsXmlGenerator", "user", None))
        self.label_18.setText(_translate("TinyowsXmlGenerator", "port", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("TinyowsXmlGenerator", "Postgresql", None))
        self.label_24.setText(_translate("TinyowsXmlGenerator", "access_constraints", None))
        self.txtMetadataName.setText(_translate("TinyowsXmlGenerator", "TinyOWS Server", None))
        self.txtMetadataTitle.setText(_translate("TinyowsXmlGenerator", "Demo", None))
        self.label_22.setText(_translate("TinyowsXmlGenerator", "keywords", None))
        self.label_23.setText(_translate("TinyowsXmlGenerator", "fees", None))
        self.label_20.setText(_translate("TinyowsXmlGenerator", "name*", None))
        self.label_21.setText(_translate("TinyowsXmlGenerator", "title*", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("TinyowsXmlGenerator", "Metadata", None))
        self.txtLayerWritable.setText(_translate("TinyowsXmlGenerator", "1", None))
        self.label_41.setText(_translate("TinyowsXmlGenerator", "ns_prefix", None))
        self.label_61.setText(_translate("TinyowsXmlGenerator", "retrievable", None))
        self.txtTinyowsLogLevel1.setText(_translate("TinyowsXmlGenerator", "writable", None))
        self.txtLayerRetrievable.setText(_translate("TinyowsXmlGenerator", "1", None))
        self.label_51.setText(_translate("TinyowsXmlGenerator", "ns_uri", None))
        self.txtLayerNsUri.setText(_translate("TinyowsXmlGenerator", "http://www.tinyows.org", None))
        self.txtLayerNsPrefix.setText(_translate("TinyowsXmlGenerator", "tows", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("TinyowsXmlGenerator", "Layer", None))

